import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms & Conditions | Duti Heritage',
  description: 'Terms and Conditions of Duti Heritage',
};

export default function TermsConditionsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16">
      <h1 className="text-3xl font-bold mb-12 uppercase tracking-widest text-center">Terms & Conditions</h1>
      
      <div className="space-y-8 text-[var(--color-text-muted)] leading-relaxed">
        <section>
          <p className="mb-4">
            This document is an electronic record under Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes under applicable Indian laws. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published and shall be construed in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and user agreement for access or usage of dutiheritage.com website.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-medium text-[var(--color-text)] mb-4 uppercase tracking-wider">User Agreement</h2>
          <p className="mb-4">
            Your use of dutiheritage.com and all the web-pages, hyper-links, tools and services provided there under (hereinafter referred to as &quot;the Website&quot; which expression shall include and successor or replacement website) is governed by the following terms and conditions as applicable to the Website (&quot;User Agreement&quot;). This User Agreement shall come into effect upon your each visit or usage of the Website or upon your registration or upon you providing any information on the Website. In this User Agreement, you are contracting with Duti Heritage LLP, hereinafter referred to as &quot;the Company&quot; which expression unless the context otherwise require shall mean and include its successors, liquidators and assigns.
          </p>
          <p className="mb-4">
            For the purpose of the User Agreement, Registered User / Visitor and wherever the context so require &apos;You&apos; shall mean any natural or legal person who has agreed to become a member of the Website by providing Registration Data (as defined hereinafter) while registering on the Website as Registered User using the computer systems of the Website or who has used the Website without becoming a Registered User, and, in both the cases, accepted this electronic version / electronic record of the User Agreement.
          </p>
          <p className="mb-4">
            As a Registered User, this User Agreement shall be effective and binding upon your &apos;acceptance&apos;. &apos;Acceptance&apos; shall mean your affirmative action in clicking on &apos;check box&apos; and /or on the &apos;continue button&apos; and/or or any affirmative action as provided on the registration page or using or accessing the Website generally in any manner, with or without using Your User ID and Password. If you do not agree or are not willing to be bound by the terms and conditions of this User Agreement, please do not seek to obtain access to or otherwise use the Website.
          </p>
          <p>
            <strong>Amendments to the User Agreement:</strong> The Company may amend this User Agreement at any time by posting a revised version on the Website. The revised version will be effective at the time Company posts it on the Website. You are advised to regularly check for any amendments or updates to the terms and conditions contained in this User Agreement.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-medium text-[var(--color-text)] mb-4 uppercase tracking-wider">Disclaimers</h2>
          <ul className="list-disc pl-5 space-y-3">
            <li>Company and its suppliers, affiliates and service providers provide the Website and services on &quot;as is&quot; basis and without any warranty or condition, express, implied or statutory and specifically disclaim any implied warranties of title, merchantability, fitness for a particular purpose and non-infringement. You expressly agree that your use of the Website is at your risk.</li>
            <li>Company, its associates, affiliates and service providers and technology partners make no representations or Warranties about the accuracy, reliability, completeness, and/or timeliness of any content, information, software, text, graphics, links or communications provided on or through the use of the Website or that the operation of the Website will be error free and/or uninterrupted.</li>
            <li>You understand, agree and acknowledge that Company uses third party services providers to store and process Your personal information and other information which You provide to the Company. Company shall not be liable for any actions, commission, omission, misconduct, fraud or negligence of these third parties.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-medium text-[var(--color-text)] mb-4 uppercase tracking-wider">Electronic Communications</h2>
          <p>
            When You use the Website or send emails or other data, information or communication to the Company, You agree and understand that You are communicating with the Website and Company and all other Registered Users and Visitors through electronic records which are legally identifiable and enforceable, and You consent to receive communications via electronic records from the Website, Company and all other Registered Users and Visitors and as and when posted, communicated or required.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-medium text-[var(--color-text)] mb-4 uppercase tracking-wider">Membership Eligibility</h2>
          <p>
            Use of the Website is available only to persons who can form legally binding contracts under Indian Contract Act, 1872 and any other applicable law for this purpose. Persons who are &quot;incompetent to contract&quot; within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Website. If you are a minor i.e. under the age of 18 years, you shall not register as a member of the Website.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-medium text-[var(--color-text)] mb-4 uppercase tracking-wider">Your Account and Registration Obligations</h2>
          <p>
            If you use the Website as Registered User, you are responsible for maintaining the confidentiality of your User ID and Password. You are responsible for all activities that occur under your User ID and Password. You agree, inter alia, to provide true, accurate, current and complete information about yourself. If you provide any information that is untrue, inaccurate, not current or incomplete, Company has the right to indefinitely suspend or terminate or block access of your membership with the Website.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-medium text-[var(--color-text)] mb-4 uppercase tracking-wider">Use of the Website</h2>
          <p>
            You understand and agree that Company and the Website merely provide services to its Registered Users and persons browsing / visiting the Website. You shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000 and rules there-under as applicable and as amended from time to time and also all applicable laws, rules and regulations and International laws regarding your use of our service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-medium text-[var(--color-text)] mb-4 uppercase tracking-wider">Privacy</h2>
          <p>
            The Company collects, stores, processes and uses Your information in accordance with Company Privacy Policy. By using the Website and/ or by providing your information, you consent to the collection and use of the information you disclose on the Website by Company in accordance with Company Privacy Policy.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-medium text-[var(--color-text)] mb-4 uppercase tracking-wider">General</h2>
          <ul className="list-disc pl-5 space-y-3">
            <li>None of the provisions of the User Agreement shall be deemed to constitute a partnership or agency between You and Company.</li>
            <li>If any clause of the User Agreement shall be deemed invalid, void or for any reason unenforceable, such clause shall be deemed severable.</li>
            <li><strong>Governing Law:</strong> This User Agreement and all the rules and policies contained herein and any of Your usage of Website and Your dealings with Company shall be governed and construed in accordance with the laws of India.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-medium text-[var(--color-text)] mb-4 uppercase tracking-wider">Arbitration</h2>
          <p>
            If any dispute arises between You and Company during Your use of the Website or Your dealing with the Company in relation to any activity on the Website, in connection with the validity, interpretation, implementation or alleged breach of any provision of the User Agreement and all the rules and policies contained herein, the dispute shall be referred to a sole arbitrator who shall be an independent and neutral third party identified by Company. The Arbitration &amp; Conciliation Act, 1996, shall govern the arbitration proceedings. The place of arbitration shall be Delhi.
          </p>
        </section>
      </div>
    </div>
  );
}
