import React from "react";

export default function TermsConditionsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16 text-gray-800">
      <h1 className="text-3xl font-bold mb-8 uppercase tracking-widest text-center">Terms & Conditions</h1>
      <div className="space-y-8 text-sm leading-relaxed">
        <p>This document is an electronic record under Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes under applicable Indian laws. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

        <section>
          <h2 className="text-xl font-semibold mb-3 uppercase tracking-wider">User Agreement</h2>
          <p>Your use of dutiheritage.co.in and all the web-pages, hyper-links, tools and services provided there under (hereinafter referred to as "the Website") is governed by the following terms and conditions. You are contracting with Duti Heritage (Proprietorship Sonia Rajput), hereinafter referred to as "the Company".</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3 uppercase tracking-wider">Disclaimers</h2>
          <p>Company and its suppliers provide the Website on "as is" basis and without any warranty or condition, express, implied or statutory. You expressly agree that your use of the Website is at your risk.</p>
        </section>
        
        <section>
          <h2 className="text-xl font-semibold mb-3 uppercase tracking-wider">Arbitration</h2>
          <p>If any dispute arises during Your use of the Website, the dispute shall be referred to a sole arbitrator who shall be an independent and neutral third party identified by Company. The place of arbitration shall be Delhi.</p>
        </section>

        <div className="mt-12 text-xs text-gray-400 text-center border-t pt-8">
          <p>Technical infrastructure and platform development by <a href="https://vinebdigital.store" target="_blank" rel="noopener noreferrer" className="underline hover:text-gray-600">Vine B Digital</a>.</p>
        </div>
      </div>
    </div>
  );
}
